### PR TITLE
Pawnmovemethod fix

### PR DESCRIPTION
**Pull request by DavidMichaelPena**
- Pawn move methods now capture correctly, moving diagonally one square only when capturing, etc.

- Pawn promotion works, auto-updating to a Queen. (option for other pieces, with UI display, to be implemented later).

- Minor tweaks to occupied? method to avoid returning nil, which was causing test to fail (after fixing  pawn methods for full functionality). 

All tests pass, ready for merge.

### CODE REVIEW

**Comment by lnzd17** [comment]
I am still able to move a pawn diagonally without it being a capture move. Do you find the same thing?

**Comment by haleymnatz** [comment]
I also can still move a pawn diagonally without capture.

**Comment by DavidMichaelPena** [comment]
I most certainly was NOT getting this! Let me make sure I push the correct/latest version :-/

**Comment by DavidMichaelPena** [comment]
Edited to correct for the capture problem. All good now, I promise! 

(The one test that it was having an issue with may need to be edited later, along with something that should be a separate branch, as it may entail more test edits, based on turn_logic. Ask if you still have any concerns or questions ).

**Pull request merged**
