### PR TITLE
Knight model

### PR DESCRIPTION
**Pull request by DavidMichaelPena**
Should be ready for merge. Passes rpsec tests. (Although I'm sure some refactoring is in its future).

### CODE REVIEW

**Comment by lnzd17** [comment]
looks good! One question though. Does the knight model have it's own tests yet?

**Comment by DavidMichaelPena** [comment]
Yes, I thought I pushed up knight test branch. I'll check.

**Comment by lnzd17** [comment]
I don't think the tests appear in this branch. I see only one file change.

**Comment by DavidMichaelPena** [comment]
I had the tests in a separate branch.

**Pull request closed without merging**
